version: '3.8'

services:
  app:
    build:
      context: .
      target: builder # Use builder stage for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - STEAM_API_KEY=${STEAM_API_KEY}
      - REALM=${REALM:-http://localhost:3000}
      - RETURN_URL=${RETURN_URL:-http://localhost:3000/auth/steam/authorize}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Optional: Limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M 